# Copyright (c) Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---
- name: RPM gpg key is present
  ansible.builtin.copy:
    src: RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    dest: /etc/pki/rpm-gpg/
    mode: '0644'

- name: RPM gpg key is imported
  ansible.builtin.rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}

- name: Package epel-release is present
  ansible.builtin.package:
    name: "{{ (epel_packages + [epel_next_package]) | unique if epel_next else epel_packages }}"

- name: Enable dependency repos
  when: epel_deps
  block:

    - name: Enable dependency repos (RHEL)
      when: ansible_distribution == 'RedHat'
      community.general.rhsm_repository:
        name: "{{ epel_repos }}"

    - name: Enable dependency repos (RHEL clones)
      when: ansible_distribution != 'RedHat'
      block:
        # better use  community.general.dnf_config_manager
        # introduced in 8.2 (ansible-core 2.15.2)
        # for now workaround to make it work on ansible-core 2.14
        - name: Get state of dependency repos (RHEL clones)
          ansible.builtin.shell: |
            set -o pipefail
            dnf repolist --enabled | grep ^{{ repo }}
          loop_control:
            loop_var: repo
          loop: "{{ epel_repos }}"
          changed_when: false
          failed_when: false
          register: __repolist

        - name: Debug
          ansible.builtin.debug:
            var: __repolist

        - name: Enable dependency repos (RHEL clones)
          when:
            - ansible_distribution_major_version is version('8', '>=')
            - __repolist.results[i].rc == 1
          ansible.builtin.command:  # noqa no-changed-when
            cmd: dnf config-manager --set-enabled {{ repo }}
          loop_control:
            loop_var: repo
            index_var: i
          loop: "{{ epel_repos }}"
...
