# vim: set ft=yaml ts=2 expandtab:
---

galaxy_info:
  role_name: devicetree
  author: Markus Falb <markus.falb@mafalb.at>
  description: installs devicetree compiler
  license: GPLv3
  min_ansible_version: '2.14'

  platforms:

    - name: Debian
      versions:
        - bullseye
        - bookworm

    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
    - name: Fedora
      versions:
        - "38"
        - "39"
        - "40"

  galaxy_tags:
    - devicetree
    - raspberry

...
