# Copyright (c) Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---
- name: Build target hostlist for epel-next
  hosts: all
  tasks:
    - name: Get eligible nodes for epel-next-release
      when:
        - ansible_distribution_major_version is version('8','>=')
        - ansible_distribution != 'Fedora'
        - ansible_os_family == 'RedHat'
      ansible.builtin.group_by:
        key: el{{ ansible_distribution_major_version }}
        parents: el8andnewer
      changed_when: false

- name: Converge epel next
  hosts: el8andnewer
  roles:
    - role: mafalb.system.epel
      epel_next: true
...
