# vim: set ft=yaml ts=2 expandtab:
#
# ___license___
---

argument_specs:
  main:
    short_description: tlp
    description:
      - tlp

    options:
      tlp_var:
        description:
          - What this var does
        type: list
        elements: str
        default:
          - default value
...
