# Copyright (c) Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---
- name: Run iconvconf
  ansible.builtin.command:
    cmd: iconvconfig
  changed_when: true

- name: Assert that charset is disabled
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      iconv -l | grep ISO-2022-CN-EXT
  register: __iconv
  changed_when: false
  failed_when: __iconv.rc == 1

- name: Assert that charset is enabled
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      iconv -l | grep ISO-2022-CN-EXT
  register: __iconv
  changed_when: false
  failed_when: __iconv.rc == 0
...
